const actionTypes = {
  PLAY_PAUSE: 'PLAY_PAUSE',
  READY_SETUP: 'READY_SETUP',
  MUTE_UNMUTE: 'MUTE_UNMUTE',
  SEEK_FORWARD: 'SEEK_FORWARD',
  SEEK_BACKWARD: 'SEEK_BACKWARD',
  SET_PLAYER_REF: 'SET_PLAYER_REF',
  DATA_AVAILABLE: 'DATA_AVAILABLE',
  SET_CURRENT_TIME: 'SET_CURRENT_TIME',
  CONTINUE_PAUSE_TIME: 'CONTINUE_PAUSE_TIME',
};

export default actionTypes;
